packages:
  - packages/**

catalog:
  "@types/node": ^22.15.24
  "@vitest/coverage-v8": ^3.1.4
  jsdom: ^26.1.0
  typescript: ^5.8.3
  vite: ^6.3.5
  vite-plugin-dts: ^4.5.4
  vite-plugin-static-copy: ^3.0.0
  vitest: ^3.1.4
  vite-plugin-solid: ^2.11.6
  solid-js: ^1.9.7

onlyBuiltDependencies:
  - esbuild

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
